import '@/app/globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import classNames from 'classnames';
import NextAuthProvider from '@/components/providers/next-auth-provider';
import Web3Provider from '@/components/providers/web3-provider';
import { CampaignProvider } from '@/context/campaign-context';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Crypto Fund',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, 'bg-darker')}>
        <NextAuthProvider>
          <Web3Provider>
            <CampaignProvider>{children}</CampaignProvider>
          </Web3Provider>
        </NextAuthProvider>
      </body>
    </html>
  );
}

// bg-gradient-to-r from-slate-900 to-slate-700
