import { Metadata } from 'next';
import { Aside } from '@/components/shared';
import DashboardNav from '@/components/shared/dashboard-nav/dashboard-nav';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const DashboardLayout = ({ children }: Props) => {
  return (
    <div className="relative sm:-8 p-4 bg-[#13131a] min-h-screen flex flex-row">
      <Aside />
      <div className="flex-1 max-sm:w-full max-w-[1280px] mx-auto sm:pr-5">
        <DashboardNav />
        {children}
      </div>
    </div>
  );
};

export default DashboardLayout;
